# Generated by Django 5.0.7 on 2024-07-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.URLField(blank=True)),
                ('cuisine', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('price', models.FloatField()),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
